// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/mind-marketplace-backend/models"
)

// GetAccountOKCode is the HTTP code returned for type GetAccountOK
const GetAccountOKCode int = 200

/*GetAccountOK successful operation

swagger:response getAccountOK
*/
type GetAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountResponse `json:"body,omitempty"`
}

// NewGetAccountOK creates GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {

	return &GetAccountOK{}
}

// WithPayload adds the payload to the get account o k response
func (o *GetAccountOK) WithPayload(payload *models.AccountResponse) *GetAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account o k response
func (o *GetAccountOK) SetPayload(payload *models.AccountResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountBadRequestCode is the HTTP code returned for type GetAccountBadRequest
const GetAccountBadRequestCode int = 400

/*GetAccountBadRequest Bad Request

swagger:response getAccountBadRequest
*/
type GetAccountBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAccountBadRequest creates GetAccountBadRequest with default headers values
func NewGetAccountBadRequest() *GetAccountBadRequest {

	return &GetAccountBadRequest{}
}

// WithPayload adds the payload to the get account bad request response
func (o *GetAccountBadRequest) WithPayload(payload *models.Error) *GetAccountBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account bad request response
func (o *GetAccountBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountInternalServerErrorCode is the HTTP code returned for type GetAccountInternalServerError
const GetAccountInternalServerErrorCode int = 500

/*GetAccountInternalServerError internal server error

swagger:response getAccountInternalServerError
*/
type GetAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAccountInternalServerError creates GetAccountInternalServerError with default headers values
func NewGetAccountInternalServerError() *GetAccountInternalServerError {

	return &GetAccountInternalServerError{}
}

// WithPayload adds the payload to the get account internal server error response
func (o *GetAccountInternalServerError) WithPayload(payload *models.Error) *GetAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account internal server error response
func (o *GetAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
