// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/bnb-chain/mind-marketplace-backend/restapi/operations/account"
	"github.com/bnb-chain/mind-marketplace-backend/restapi/operations/item"
	"github.com/bnb-chain/mind-marketplace-backend/restapi/operations/purchase"
)

// NewMindMarketplaceAPI creates a new MindMarketplace instance
func NewMindMarketplaceAPI(spec *loads.Document) *MindMarketplaceAPI {
	return &MindMarketplaceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ItemBatchItemHandler: item.BatchItemHandlerFunc(func(params item.BatchItemParams) middleware.Responder {
			return middleware.NotImplemented("operation item.BatchItem has not yet been implemented")
		}),
		AccountGetAccountHandler: account.GetAccountHandlerFunc(func(params account.GetAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation account.GetAccount has not yet been implemented")
		}),
		ItemGetCategoryHandler: item.GetCategoryHandlerFunc(func(params item.GetCategoryParams) middleware.Responder {
			return middleware.NotImplemented("operation item.GetCategory has not yet been implemented")
		}),
		ItemGetItemHandler: item.GetItemHandlerFunc(func(params item.GetItemParams) middleware.Responder {
			return middleware.NotImplemented("operation item.GetItem has not yet been implemented")
		}),
		ItemGetItemByBucketHandler: item.GetItemByBucketHandlerFunc(func(params item.GetItemByBucketParams) middleware.Responder {
			return middleware.NotImplemented("operation item.GetItemByBucket has not yet been implemented")
		}),
		ItemGetItemByGroupHandler: item.GetItemByGroupHandlerFunc(func(params item.GetItemByGroupParams) middleware.Responder {
			return middleware.NotImplemented("operation item.GetItemByGroup has not yet been implemented")
		}),
		ItemGetItemByObjectHandler: item.GetItemByObjectHandlerFunc(func(params item.GetItemByObjectParams) middleware.Responder {
			return middleware.NotImplemented("operation item.GetItemByObject has not yet been implemented")
		}),
		PurchaseGetPurchaseHandler: purchase.GetPurchaseHandlerFunc(func(params purchase.GetPurchaseParams) middleware.Responder {
			return middleware.NotImplemented("operation purchase.GetPurchase has not yet been implemented")
		}),
		ItemSearchItemHandler: item.SearchItemHandlerFunc(func(params item.SearchItemParams) middleware.Responder {
			return middleware.NotImplemented("operation item.SearchItem has not yet been implemented")
		}),
		PurchaseSearchPurchaseHandler: purchase.SearchPurchaseHandlerFunc(func(params purchase.SearchPurchaseParams) middleware.Responder {
			return middleware.NotImplemented("operation purchase.SearchPurchase has not yet been implemented")
		}),
		AccountUpdateAccountHandler: account.UpdateAccountHandlerFunc(func(params account.UpdateAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation account.UpdateAccount has not yet been implemented")
		}),
	}
}

/*MindMarketplaceAPI Swagger document for data marketplace apis. */
type MindMarketplaceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ItemBatchItemHandler sets the operation handler for the batch item operation
	ItemBatchItemHandler item.BatchItemHandler
	// AccountGetAccountHandler sets the operation handler for the get account operation
	AccountGetAccountHandler account.GetAccountHandler
	// ItemGetCategoryHandler sets the operation handler for the get category operation
	ItemGetCategoryHandler item.GetCategoryHandler
	// ItemGetItemHandler sets the operation handler for the get item operation
	ItemGetItemHandler item.GetItemHandler
	// ItemGetItemByBucketHandler sets the operation handler for the get item by bucket operation
	ItemGetItemByBucketHandler item.GetItemByBucketHandler
	// ItemGetItemByGroupHandler sets the operation handler for the get item by group operation
	ItemGetItemByGroupHandler item.GetItemByGroupHandler
	// ItemGetItemByObjectHandler sets the operation handler for the get item by object operation
	ItemGetItemByObjectHandler item.GetItemByObjectHandler
	// PurchaseGetPurchaseHandler sets the operation handler for the get purchase operation
	PurchaseGetPurchaseHandler purchase.GetPurchaseHandler
	// ItemSearchItemHandler sets the operation handler for the search item operation
	ItemSearchItemHandler item.SearchItemHandler
	// PurchaseSearchPurchaseHandler sets the operation handler for the search purchase operation
	PurchaseSearchPurchaseHandler purchase.SearchPurchaseHandler
	// AccountUpdateAccountHandler sets the operation handler for the update account operation
	AccountUpdateAccountHandler account.UpdateAccountHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *MindMarketplaceAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *MindMarketplaceAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *MindMarketplaceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MindMarketplaceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MindMarketplaceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MindMarketplaceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MindMarketplaceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MindMarketplaceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MindMarketplaceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MindMarketplaceAPI
func (o *MindMarketplaceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ItemBatchItemHandler == nil {
		unregistered = append(unregistered, "item.BatchItemHandler")
	}
	if o.AccountGetAccountHandler == nil {
		unregistered = append(unregistered, "account.GetAccountHandler")
	}
	if o.ItemGetCategoryHandler == nil {
		unregistered = append(unregistered, "item.GetCategoryHandler")
	}
	if o.ItemGetItemHandler == nil {
		unregistered = append(unregistered, "item.GetItemHandler")
	}
	if o.ItemGetItemByBucketHandler == nil {
		unregistered = append(unregistered, "item.GetItemByBucketHandler")
	}
	if o.ItemGetItemByGroupHandler == nil {
		unregistered = append(unregistered, "item.GetItemByGroupHandler")
	}
	if o.ItemGetItemByObjectHandler == nil {
		unregistered = append(unregistered, "item.GetItemByObjectHandler")
	}
	if o.PurchaseGetPurchaseHandler == nil {
		unregistered = append(unregistered, "purchase.GetPurchaseHandler")
	}
	if o.ItemSearchItemHandler == nil {
		unregistered = append(unregistered, "item.SearchItemHandler")
	}
	if o.PurchaseSearchPurchaseHandler == nil {
		unregistered = append(unregistered, "purchase.SearchPurchaseHandler")
	}
	if o.AccountUpdateAccountHandler == nil {
		unregistered = append(unregistered, "account.UpdateAccountHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MindMarketplaceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MindMarketplaceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *MindMarketplaceAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *MindMarketplaceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *MindMarketplaceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MindMarketplaceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the mind marketplace API
func (o *MindMarketplaceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MindMarketplaceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/item/batch"] = item.NewBatchItem(o.context, o.ItemBatchItemHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/{address}"] = account.NewGetAccount(o.context, o.AccountGetAccountHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item/categories"] = item.NewGetCategory(o.context, o.ItemGetCategoryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item/{itemId}"] = item.NewGetItem(o.context, o.ItemGetItemHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item_by_bucket/{bucketId}"] = item.NewGetItemByBucket(o.context, o.ItemGetItemByBucketHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item_by_group/{groupId}"] = item.NewGetItemByGroup(o.context, o.ItemGetItemByGroupHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/item_by_object/{objectId}"] = item.NewGetItemByObject(o.context, o.ItemGetItemByObjectHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/purchase/{purchaseId}"] = purchase.NewGetPurchase(o.context, o.PurchaseGetPurchaseHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/item/search"] = item.NewSearchItem(o.context, o.ItemSearchItemHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/purchase/search"] = purchase.NewSearchPurchase(o.context, o.PurchaseSearchPurchaseHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/account/update"] = account.NewUpdateAccount(o.context, o.AccountUpdateAccountHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MindMarketplaceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MindMarketplaceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MindMarketplaceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MindMarketplaceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *MindMarketplaceAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
