// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Data Marketplace
//
//  Swagger document for data marketplace apis.
//  Schemes:
//    http
//  Host: 127.0.0.1:8080
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
