insert into categories(id, name) values (100, 'Uncategorized');
insert into categories(id, name) values (1, 'AI Model');
insert into categories(id, name) values (2, 'Code Resource');
insert into categories(id, name) values (3, 'Digital Media');
insert into categories(id, name) values (4, 'Literary Creation');
insert into categories(id, name) values (5, 'Scientific Data');
insert into categories(id, name) values (6, 'Game');
insert into categories(id, name) values (7, 'AIGC');
insert into categories(id, name) values (8, 'Education');
insert into categories(id, name) values (9, 'Finance');