// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPurchaseHandlerFunc turns a function with the right signature into a get purchase handler
type GetPurchaseHandlerFunc func(GetPurchaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPurchaseHandlerFunc) Handle(params GetPurchaseParams) middleware.Responder {
	return fn(params)
}

// GetPurchaseHandler interface for that can handle valid get purchase params
type GetPurchaseHandler interface {
	Handle(GetPurchaseParams) middleware.Responder
}

// NewGetPurchase creates a new http.Handler for the get purchase operation
func NewGetPurchase(ctx *middleware.Context, handler GetPurchaseHandler) *GetPurchase {
	return &GetPurchase{Context: ctx, Handler: handler}
}

/* GetPurchase swagger:route GET /purchase/{purchaseId} purchase getPurchase

Get purchase

*/
type GetPurchase struct {
	Context *middleware.Context
	Handler GetPurchaseHandler
}

func (o *GetPurchase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPurchaseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
