// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/mind-marketplace-backend/models"
)

// GetPurchaseOKCode is the HTTP code returned for type GetPurchaseOK
const GetPurchaseOKCode int = 200

/*GetPurchaseOK successful operation

swagger:response getPurchaseOK
*/
type GetPurchaseOK struct {

	/*
	  In: Body
	*/
	Payload *models.PurchaseResponse `json:"body,omitempty"`
}

// NewGetPurchaseOK creates GetPurchaseOK with default headers values
func NewGetPurchaseOK() *GetPurchaseOK {

	return &GetPurchaseOK{}
}

// WithPayload adds the payload to the get purchase o k response
func (o *GetPurchaseOK) WithPayload(payload *models.PurchaseResponse) *GetPurchaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get purchase o k response
func (o *GetPurchaseOK) SetPayload(payload *models.PurchaseResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPurchaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPurchaseBadRequestCode is the HTTP code returned for type GetPurchaseBadRequest
const GetPurchaseBadRequestCode int = 400

/*GetPurchaseBadRequest Bad Request

swagger:response getPurchaseBadRequest
*/
type GetPurchaseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPurchaseBadRequest creates GetPurchaseBadRequest with default headers values
func NewGetPurchaseBadRequest() *GetPurchaseBadRequest {

	return &GetPurchaseBadRequest{}
}

// WithPayload adds the payload to the get purchase bad request response
func (o *GetPurchaseBadRequest) WithPayload(payload *models.Error) *GetPurchaseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get purchase bad request response
func (o *GetPurchaseBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPurchaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPurchaseInternalServerErrorCode is the HTTP code returned for type GetPurchaseInternalServerError
const GetPurchaseInternalServerErrorCode int = 500

/*GetPurchaseInternalServerError internal server error

swagger:response getPurchaseInternalServerError
*/
type GetPurchaseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPurchaseInternalServerError creates GetPurchaseInternalServerError with default headers values
func NewGetPurchaseInternalServerError() *GetPurchaseInternalServerError {

	return &GetPurchaseInternalServerError{}
}

// WithPayload adds the payload to the get purchase internal server error response
func (o *GetPurchaseInternalServerError) WithPayload(payload *models.Error) *GetPurchaseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get purchase internal server error response
func (o *GetPurchaseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPurchaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
