// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// QueryPurchaseHandlerFunc turns a function with the right signature into a query purchase handler
type QueryPurchaseHandlerFunc func(QueryPurchaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn QueryPurchaseHandlerFunc) Handle(params QueryPurchaseParams) middleware.Responder {
	return fn(params)
}

// QueryPurchaseHandler interface for that can handle valid query purchase params
type QueryPurchaseHandler interface {
	Handle(QueryPurchaseParams) middleware.Responder
}

// NewQueryPurchase creates a new http.Handler for the query purchase operation
func NewQueryPurchase(ctx *middleware.Context, handler QueryPurchaseHandler) *QueryPurchase {
	return &QueryPurchase{Context: ctx, Handler: handler}
}

/* QueryPurchase swagger:route POST /purchase/query purchase queryPurchase

Query purchase

*/
type QueryPurchase struct {
	Context *middleware.Context
	Handler QueryPurchaseHandler
}

func (o *QueryPurchase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewQueryPurchaseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
