// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SearchPurchaseHandlerFunc turns a function with the right signature into a search purchase handler
type SearchPurchaseHandlerFunc func(SearchPurchaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchPurchaseHandlerFunc) Handle(params SearchPurchaseParams) middleware.Responder {
	return fn(params)
}

// SearchPurchaseHandler interface for that can handle valid search purchase params
type SearchPurchaseHandler interface {
	Handle(SearchPurchaseParams) middleware.Responder
}

// NewSearchPurchase creates a new http.Handler for the search purchase operation
func NewSearchPurchase(ctx *middleware.Context, handler SearchPurchaseHandler) *SearchPurchase {
	return &SearchPurchase{Context: ctx, Handler: handler}
}

/* SearchPurchase swagger:route POST /purchase/search purchase searchPurchase

Search purchase

*/
type SearchPurchase struct {
	Context *middleware.Context
	Handler SearchPurchaseHandler
}

func (o *SearchPurchase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSearchPurchaseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
