// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// BatchItemHandlerFunc turns a function with the right signature into a batch item handler
type BatchItemHandlerFunc func(BatchItemParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BatchItemHandlerFunc) Handle(params BatchItemParams) middleware.Responder {
	return fn(params)
}

// BatchItemHandler interface for that can handle valid batch item params
type BatchItemHandler interface {
	Handle(BatchItemParams) middleware.Responder
}

// NewBatchItem creates a new http.Handler for the batch item operation
func NewBatchItem(ctx *middleware.Context, handler BatchItemHandler) *BatchItem {
	return &BatchItem{Context: ctx, Handler: handler}
}

/* BatchItem swagger:route POST /item/batch item batchItem

Get items in batch

*/
type BatchItem struct {
	Context *middleware.Context
	Handler BatchItemHandler
}

func (o *BatchItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewBatchItemParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
