// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetItemByBucketsHandlerFunc turns a function with the right signature into a get item by buckets handler
type GetItemByBucketsHandlerFunc func(GetItemByBucketsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemByBucketsHandlerFunc) Handle(params GetItemByBucketsParams) middleware.Responder {
	return fn(params)
}

// GetItemByBucketsHandler interface for that can handle valid get item by buckets params
type GetItemByBucketsHandler interface {
	Handle(GetItemByBucketsParams) middleware.Responder
}

// NewGetItemByBuckets creates a new http.Handler for the get item by buckets operation
func NewGetItemByBuckets(ctx *middleware.Context, handler GetItemByBucketsHandler) *GetItemByBuckets {
	return &GetItemByBuckets{Context: ctx, Handler: handler}
}

/* GetItemByBuckets swagger:route POST /item_by_buckets item getItemByBuckets

Get items by buckets

*/
type GetItemByBuckets struct {
	Context *middleware.Context
	Handler GetItemByBucketsHandler
}

func (o *GetItemByBuckets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetItemByBucketsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
