// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetItemByBucketHandlerFunc turns a function with the right signature into a get item by bucket handler
type GetItemByBucketHandlerFunc func(GetItemByBucketParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemByBucketHandlerFunc) Handle(params GetItemByBucketParams) middleware.Responder {
	return fn(params)
}

// GetItemByBucketHandler interface for that can handle valid get item by bucket params
type GetItemByBucketHandler interface {
	Handle(GetItemByBucketParams) middleware.Responder
}

// NewGetItemByBucket creates a new http.Handler for the get item by bucket operation
func NewGetItemByBucket(ctx *middleware.Context, handler GetItemByBucketHandler) *GetItemByBucket {
	return &GetItemByBucket{Context: ctx, Handler: handler}
}

/* GetItemByBucket swagger:route GET /item_by_bucket/{bucketId} item getItemByBucket

Get item by bucket

*/
type GetItemByBucket struct {
	Context *middleware.Context
	Handler GetItemByBucketHandler
}

func (o *GetItemByBucket) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetItemByBucketParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
