// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetItemByGroupHandlerFunc turns a function with the right signature into a get item by group handler
type GetItemByGroupHandlerFunc func(GetItemByGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemByGroupHandlerFunc) Handle(params GetItemByGroupParams) middleware.Responder {
	return fn(params)
}

// GetItemByGroupHandler interface for that can handle valid get item by group params
type GetItemByGroupHandler interface {
	Handle(GetItemByGroupParams) middleware.Responder
}

// NewGetItemByGroup creates a new http.Handler for the get item by group operation
func NewGetItemByGroup(ctx *middleware.Context, handler GetItemByGroupHandler) *GetItemByGroup {
	return &GetItemByGroup{Context: ctx, Handler: handler}
}

/* GetItemByGroup swagger:route GET /item_by_group/{groupId} item getItemByGroup

Get item by group

*/
type GetItemByGroup struct {
	Context *middleware.Context
	Handler GetItemByGroupHandler
}

func (o *GetItemByGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetItemByGroupParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
