// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetItemParams creates a new GetItemParams object
//
// There are no default values defined in the spec.
func NewGetItemParams() GetItemParams {

	return GetItemParams{}
}

// GetItemParams contains all the bound params for the get item operation
// typically these are obtained from a http.Request
//
// swagger:parameters getItem
type GetItemParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*id of item
	  Required: true
	  In: path
	*/
	ItemID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetItemParams() beforehand.
func (o *GetItemParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rItemID, rhkItemID, _ := route.Params.GetOK("itemId")
	if err := o.bindItemID(rItemID, rhkItemID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindItemID binds and validates parameter ItemID from path.
func (o *GetItemParams) bindItemID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("itemId", "path", "int64", raw)
	}
	o.ItemID = value

	return nil
}
