// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/mind-marketplace-backend/models"
)

// GetCategoryOKCode is the HTTP code returned for type GetCategoryOK
const GetCategoryOKCode int = 200

/*GetCategoryOK successful operation

swagger:response getCategoryOK
*/
type GetCategoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListCategoryResponse `json:"body,omitempty"`
}

// NewGetCategoryOK creates GetCategoryOK with default headers values
func NewGetCategoryOK() *GetCategoryOK {

	return &GetCategoryOK{}
}

// WithPayload adds the payload to the get category o k response
func (o *GetCategoryOK) WithPayload(payload *models.ListCategoryResponse) *GetCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category o k response
func (o *GetCategoryOK) SetPayload(payload *models.ListCategoryResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCategoryBadRequestCode is the HTTP code returned for type GetCategoryBadRequest
const GetCategoryBadRequestCode int = 400

/*GetCategoryBadRequest Bad Request

swagger:response getCategoryBadRequest
*/
type GetCategoryBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCategoryBadRequest creates GetCategoryBadRequest with default headers values
func NewGetCategoryBadRequest() *GetCategoryBadRequest {

	return &GetCategoryBadRequest{}
}

// WithPayload adds the payload to the get category bad request response
func (o *GetCategoryBadRequest) WithPayload(payload *models.Error) *GetCategoryBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category bad request response
func (o *GetCategoryBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCategoryInternalServerErrorCode is the HTTP code returned for type GetCategoryInternalServerError
const GetCategoryInternalServerErrorCode int = 500

/*GetCategoryInternalServerError internal server error

swagger:response getCategoryInternalServerError
*/
type GetCategoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCategoryInternalServerError creates GetCategoryInternalServerError with default headers values
func NewGetCategoryInternalServerError() *GetCategoryInternalServerError {

	return &GetCategoryInternalServerError{}
}

// WithPayload adds the payload to the get category internal server error response
func (o *GetCategoryInternalServerError) WithPayload(payload *models.Error) *GetCategoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category internal server error response
func (o *GetCategoryInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
