// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetItemByBucketParams creates a new GetItemByBucketParams object
//
// There are no default values defined in the spec.
func NewGetItemByBucketParams() GetItemByBucketParams {

	return GetItemByBucketParams{}
}

// GetItemByBucketParams contains all the bound params for the get item by bucket operation
// typically these are obtained from a http.Request
//
// swagger:parameters getItemByBucket
type GetItemByBucketParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*bucket id
	  Required: true
	  In: path
	*/
	BucketID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetItemByBucketParams() beforehand.
func (o *GetItemByBucketParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBucketID, rhkBucketID, _ := route.Params.GetOK("bucketId")
	if err := o.bindBucketID(rBucketID, rhkBucketID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBucketID binds and validates parameter BucketID from path.
func (o *GetItemByBucketParams) bindBucketID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("bucketId", "path", "int64", raw)
	}
	o.BucketID = value

	return nil
}
