// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/greenfield-data-marketplace-backend/models"
)

// GetItemOKCode is the HTTP code returned for type GetItemOK
const GetItemOKCode int = 200

/*GetItemOK successful operation

swagger:response getItemOK
*/
type GetItemOK struct {

	/*
	  In: Body
	*/
	Payload *models.ItemResponse `json:"body,omitempty"`
}

// NewGetItemOK creates GetItemOK with default headers values
func NewGetItemOK() *GetItemOK {

	return &GetItemOK{}
}

// WithPayload adds the payload to the get item o k response
func (o *GetItemOK) WithPayload(payload *models.ItemResponse) *GetItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item o k response
func (o *GetItemOK) SetPayload(payload *models.ItemResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetItemBadRequestCode is the HTTP code returned for type GetItemBadRequest
const GetItemBadRequestCode int = 400

/*GetItemBadRequest Bad Request

swagger:response getItemBadRequest
*/
type GetItemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetItemBadRequest creates GetItemBadRequest with default headers values
func NewGetItemBadRequest() *GetItemBadRequest {

	return &GetItemBadRequest{}
}

// WithPayload adds the payload to the get item bad request response
func (o *GetItemBadRequest) WithPayload(payload *models.Error) *GetItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item bad request response
func (o *GetItemBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetItemInternalServerErrorCode is the HTTP code returned for type GetItemInternalServerError
const GetItemInternalServerErrorCode int = 500

/*GetItemInternalServerError internal server error

swagger:response getItemInternalServerError
*/
type GetItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetItemInternalServerError creates GetItemInternalServerError with default headers values
func NewGetItemInternalServerError() *GetItemInternalServerError {

	return &GetItemInternalServerError{}
}

// WithPayload adds the payload to the get item internal server error response
func (o *GetItemInternalServerError) WithPayload(payload *models.Error) *GetItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item internal server error response
func (o *GetItemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
