// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bnb-chain/greenfield-data-marketplace-backend/models"
)

// SearchItemOKCode is the HTTP code returned for type SearchItemOK
const SearchItemOKCode int = 200

/*SearchItemOK successful operation

swagger:response searchItemOK
*/
type SearchItemOK struct {

	/*
	  In: Body
	*/
	Payload *models.PageItemResponse `json:"body,omitempty"`
}

// NewSearchItemOK creates SearchItemOK with default headers values
func NewSearchItemOK() *SearchItemOK {

	return &SearchItemOK{}
}

// WithPayload adds the payload to the search item o k response
func (o *SearchItemOK) WithPayload(payload *models.PageItemResponse) *SearchItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search item o k response
func (o *SearchItemOK) SetPayload(payload *models.PageItemResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SearchItemBadRequestCode is the HTTP code returned for type SearchItemBadRequest
const SearchItemBadRequestCode int = 400

/*SearchItemBadRequest Bad Request

swagger:response searchItemBadRequest
*/
type SearchItemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSearchItemBadRequest creates SearchItemBadRequest with default headers values
func NewSearchItemBadRequest() *SearchItemBadRequest {

	return &SearchItemBadRequest{}
}

// WithPayload adds the payload to the search item bad request response
func (o *SearchItemBadRequest) WithPayload(payload *models.Error) *SearchItemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search item bad request response
func (o *SearchItemBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SearchItemInternalServerErrorCode is the HTTP code returned for type SearchItemInternalServerError
const SearchItemInternalServerErrorCode int = 500

/*SearchItemInternalServerError internal server error

swagger:response searchItemInternalServerError
*/
type SearchItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSearchItemInternalServerError creates SearchItemInternalServerError with default headers values
func NewSearchItemInternalServerError() *SearchItemInternalServerError {

	return &SearchItemInternalServerError{}
}

// WithPayload adds the payload to the search item internal server error response
func (o *SearchItemInternalServerError) WithPayload(payload *models.Error) *SearchItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search item internal server error response
func (o *SearchItemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
