// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SearchItemHandlerFunc turns a function with the right signature into a search item handler
type SearchItemHandlerFunc func(SearchItemParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchItemHandlerFunc) Handle(params SearchItemParams) middleware.Responder {
	return fn(params)
}

// SearchItemHandler interface for that can handle valid search item params
type SearchItemHandler interface {
	Handle(SearchItemParams) middleware.Responder
}

// NewSearchItem creates a new http.Handler for the search item operation
func NewSearchItem(ctx *middleware.Context, handler SearchItemHandler) *SearchItem {
	return &SearchItem{Context: ctx, Handler: handler}
}

/* SearchItem swagger:route POST /item/search item searchItem

Search item

*/
type SearchItem struct {
	Context *middleware.Context
	Handler SearchItemHandler
}

func (o *SearchItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSearchItemParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
